### ISSUE TITLE
Can't edit menu links

### ISSUE THREAD

**Issue by drupdotes** [govCMS/govcms8-installer#302]
GovCMS fresh install (git clone).
"The website encountered an unexpected error. Please try again later." message is shown if you try to edit a menu link.
Apache/2.4.29.
PHP/7.2.19.
MySQL/5.7.26

> [php7:notice] [pid 2815] [client 127.0.0.1:48062] TypeError: Argument 1 passed to Drupal\\Core\\Access\\AccessResult::orIf() must implement interface Drupal\\Core\\Access\\AccessResultInterface, null given, called in /path/to/main.govcms/docroot/core/lib/Drupal/Core/Entity/EntityAccessControlHandler.php on line 105 in /path/to/main.govcms/docroot/core/lib/Drupal/Core/Access/AccessResult.php on line 314 #0 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Entity/EntityAccessControlHandler.php(105): Drupal\\Core\\Access\\AccessResult->orIf(NULL)\n#1 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Entity/ContentEntityBase.php(709): Drupal\\Core\\Entity\\EntityAccessControlHandler->access(Object(Drupal\\menu_link_content\\Entity\\MenuLinkContent), 'view scheduled ...', Object(Drupal\\Core\\Session\\AccountProxy), true)\n#2 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Entity/EntityAccessCheck.php(65): Drupal\\Core\\Entity\\ContentEntityBase->access('view scheduled ...', Object(Drupal\\Core\\Session\\AccountProxy), true)\n#3 [internal function]: Drupal\\Core\\Entity\\EntityAccessCheck->access(Object(Symfony\\Component\\Routing\\Route), Object(Drupal\\Core\\Routing\\RouteMatch), Object(Drupal\\Core\\Session\\AccountProxy))\n#4 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Access/AccessManager.php(159): call_user_func_array(Array, Array)\n#5 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Access/AccessManager.php(135): Drupal\\Core\\Access\\AccessManager->performCheck('access_check.en...', Object(Drupal\\Component\\Utility\\ArgumentsResolver))\n#6 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Access/AccessManager.php(92): Drupal\\Core\\Access\\AccessManager->check(Object(Drupal\\Core\\Routing\\RouteMatch), Object(Drupal\\Core\\Session\\AccountProxy), NULL, true)\n#7 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Menu/LocalTaskManager.php(347): Drupal\\Core\\Access\\AccessManager->checkNamedRoute('entity.menu_lin...', Array, Object(Drupal\\Core\\Session\\AccountProxy), true)\n#8 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Menu/LocalTaskManager.php(378): Drupal\\Core\\Menu\\LocalTaskManager->getTasksBuild('entity.menu_lin...', Object(Drupal\\Core\\Cache\\CacheableMetadata))\n#9 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Menu/Plugin/Block/LocalTasksBlock.php(95): Drupal\\Core\\Menu\\LocalTaskManager->getLocalTasks('entity.menu_lin...', 0)\n#10 /path/to/main.govcms/docroot/core/modules/block/src/BlockViewBuilder.php(163): Drupal\\Core\\Menu\\Plugin\\Block\\LocalTasksBlock->build()\n#11 [internal function]: Drupal\\block\\BlockViewBuilder::preRender(Array)\n#12 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Render/Renderer.php(378): call_user_func('Drupal\\\\block\\\\Bl...', Array)\n#13 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Render/Renderer.php(450): Drupal\\Core\\Render\\Renderer->doRender(Array)\n#14 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#15 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Template/TwigExtension.php(501): Drupal\\Core\\Render\\Renderer->render(Array)\n#16 /path/to/main.govcms/docroot/sites/default/files/php/twig/5d1f630fef81d_page.html.twig_v8zUTD7qy-EMCtKbn_kPzpHVw/ESHJeZuvAQX3m_cmRvjLxpxtPNKGUgY0xjeb8apTzrs.php(59): Drupal\\Core\\Template\\TwigExtension->escapeFilter(Object(Drupal\\Core\\Template\\TwigEnvironment), Array, 'html', NULL, true)\n#17 /path/to/main.govcms/vendor/twig/twig/src/Template.php(455): __TwigTemplate_c85f4b6cd268d1a50fa3aeeca4c6b258c7ed967e6467e674e202b3e0564da44f->doDisplay(Array, Array)\n#18 /path/to/main.govcms/vendor/twig/twig/src/Template.php(422): Twig\\Template->displayWithErrorHandling(Array, Array)\n#19 /path/to/main.govcms/vendor/twig/twig/src/Template.php(434): Twig\\Template->display(Array)\n#20 /path/to/main.govcms/docroot/core/themes/engines/twig/twig.engine(64): Twig\\Template->render(Array)\n#21 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('core/themes/sev...', Array)\n#22 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\\Core\\Theme\\ThemeManager->render('page', Array)\n#23 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#24 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Template/TwigExtension.php(501): Drupal\\Core\\Render\\Renderer->render(Array)\n#25 /path/to/main.govcms/docroot/sites/default/files/php/twig/5d1f630fef81d_html.html.twig_W43WXTfD47o0mP1WbGVAE31ld/SMi93i7kpWn7snrXUGJ3frXb1vZjjYe1h7y9WaLBWCw.php(102): Drupal\\Core\\Template\\TwigExtension->escapeFilter(Object(Drupal\\Core\\Template\\TwigEnvironment), Array, 'html', NULL, true)\n#26 /path/to/main.govcms/vendor/twig/twig/src/Template.php(455): __TwigTemplate_664cab686d874acd433874fdf3064d78620e9cf527cbbb5f30afaa9c5c9cce61->doDisplay(Array, Array)\n#27 /path/to/main.govcms/vendor/twig/twig/src/Template.php(422): Twig\\Template->displayWithErrorHandling(Array, Array)\n#28 /path/to/main.govcms/vendor/twig/twig/src/Template.php(434): Twig\\Template->display(Array)\n#29 /path/to/main.govcms/docroot/core/themes/engines/twig/twig.engine(64): Twig\\Template->render(Array)\n#30 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('core/themes/cla...', Array)\n#31 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\\Core\\Theme\\ThemeManager->render('html', Array)\n#32 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#33 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(147): Drupal\\Core\\Render\\Renderer->render(Array)\n#34 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->Drupal\\Core\\Render\\MainContent\\{closure}()\n#35 /path/to/main.govcms/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(148): Drupal\\Core\\Render\\Renderer->executeInRenderContext(Object(Drupal\\Core\\Render\\RenderContext), Object(Closure))\n#36 /path/to/main.govcms/docroot/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->renderResponse(Array, Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Routing\\CurrentRouteMatch))\n#37 [internal function]: Drupal\\Core\\EventSubscriber\\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#38 /path/to/main.govcms/docroot/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#39 /path/to/main.govcms/vendor/symfony/http-kernel/HttpKernel.php(156): Drupal\\Compo

**Comment by gargsuchi** [comment]
Hi @drupdotes 
Have you enabled the Scheduled Transitions module? This bug is documented here https://www.drupal.org/project/scheduled_transitions/issues/3043098

Please disable the module.

**Comment by mikekreuzer** [comment]
Hi, the module comes enabled in govcms8-scaffold, it's required by GovCMS Content Types; turning it off means ditching those. That does fix the problem though, cheers, Mike

**Comment by gargsuchi** [comment]
That's right @mikekreuzer . If you are installing govcms from scratch - it becomes a bit difficult to disable the module.

**Comment by simesy** [comment]
Yeah pain in the bot

**Comment by brett-sargeant** [comment]
Last time I set up a new site, the module was there, but not enabled so wasn't affecting anything.

**Comment by gargsuchi** [comment]
@simesy There is a patch here - https://www.drupal.org/project/drupal/issues/3016038
Yes - the issue is still "Needs Work" but the changes required are in the tests. So - should consider putting the patch is govcms.

**Comment by simesy** [comment]
thanks Suchi, referenced here https://www.drupal.org/project/govcms8/issues/3047291#comment-13262122

I agree it would be good as a patch, but I don't think patches are a practical solution for govcms SaaS at this point.

**Comment by brett-sargeant** [comment]
Any news on when this fix is likely to be available in GovCMS 8 SaaS?

**Comment by simesy** [comment]
@AMDS ?

**Comment by AlexSkrypnyk** [comment]
We just hit this one as well. Can this patch be included in the next release please?

**Comment by klonos** [comment]
Yeah, this one was creeping up on us very often while doing training back in October/November last year 😔

**Comment by stooit** [comment]
+1 for the patch; atm you can choose between a functional menu system and the GovCMS-provided content types.

FWIW the updated patch in #20 has vastly reduced the scope, it adds 2 lines of functional change needing review.

I've tested this patch and confirm it resolves the underlying issue. Filed a PR here: https://github.com/govCMS/govCMS8/pull/462
